version: '3.8'
services:
  postgres:
    image: postgres:13.1
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
    container_name: postgres

volumes:
  postgres:
